// Survey table + field IDs in the Summer Intensives Airtable base.
// Generated by scripts/create_survey_tables.py.

export const SURVEY_BASE_ID = process.env.AIRTABLE_BASE_ID!;
export const APPLICATIONS_TABLE_ID =
  process.env.AIRTABLE_TABLE_ID || "tblzpCIOIsRpfJryh";

export const SURVEY = {
  intake: {
    tableId: "tblVi3jowYcdbu4bj",
    fields: {
      submissionId: "fldbuzFYa3NgymuiS",
      participant: "flds1gw0MYOjuXZhl",
      submittedAt: "fldZMZCBXlS3xWYN6",
      priorExposure: "fldIB3luUzsoMCAMk",
      counterfactual: "fldoTbsCJlA9MPLAu",
      knowledgeAis: "fldP7E73Mki9WCc00",
      knowledgeEvals: "fld2rjLXJkUVMhhYx",
      knowledgeFt: "fldDo5zEe96L3ZfAV",
      knowledgeMech: "fldDBnkLTc6aODEW6",
      fieldFit: "fldwJXCA4mYlY4oYn",
      careerClarity: "fld10rSnl4aq2p3qq",
      hoursPerWeek: "fldW9oj2786IPXN2s",
      careerBucket: "fldDWuJ7vNtEWD6f1",
      careerBucketOther: "fldmYKHeG99AoZPsZ",
      dietaryRestrictions: "fldGsKJa34v9R3eJx",
      pronouns: "fldzN9aWGQ2WJUpTM",
    },
  },
  pulse: {
    tableId: "tblR1zpLyNl0uvnrB",
    fields: {
      submissionId: "fldB8JUBN5SR4qEwq",
      participant: "fldrxYMV3e1RkkU2o",
      submittedAt: "fldqEpHjOFYbNdgv7",
      week: "fldIcDe2VEH2MzTMW",
      dayNps: "fldDOROuBb2Yzjm4P",
      bestPart: "fldN3tf6ZwBDEolIR",
      whatChange: "fldd2ASSeJRhKJHpX",
      anythingElse: "fldpIGf0YYMcYuGn1",
    },
  },
  exit: {
    tableId: "tblRtd6U9JlpU4rNi",
    fields: {
      submissionId: "fldKoAK0astWB4vO1",
      participant: "fld4KBx8AIIkY0jr4",
      submittedAt: "fldEjRr9etVlWAAjk",
      knowledgeAis: "flddUpfzMyqTJgOKZ",
      knowledgeEvals: "fldp6ejLuiQbsC0F9",
      knowledgeFt: "fldltFhHUQo6t7wQP",
      knowledgeMech: "fldzvXo1zBjxB6rYX",
      fieldFit: "fldCwk2uaM4Ag0SI5",
      careerClarity: "fld59nbtqDxxzH8Fc",
      careerBucket: "fld8dQ9JnjwvkzMZY",
      careerBucketOther: "fldqXWgE991MZClDL",
      commitment: "fldrF8zfEPZLsyBo2",
      stayInTouch: "fld0GvvGlELx2ByFA",
      favouriteParts: "fldXbgW3NUcFU82UH",
      favouritePartsOther: "fldunFYGxfcXE6kT8",
      mostValuableWeek: "fldDF9oBi0xHaG50X",
      whyMostValuable: "fldGlXBm8TuCGJL6v",
      doubleDownOn: "fldGT450H43seQNX8",
      cutOrChange: "fldLKeP4A9P2xtfUI",
      peopleToCallOut: "fld3ehnwavrVlGf13",
      programNps: "fldb7yg8Z6icrk9Fc",
      anythingElse: "fldl46kMU9gwNes9D",
      referrals: "fldF29wOSX1HqpzYQ",
      futureHelp: "fld4xrErSkGp2Xn4F",
      testimonial: "fldw3owoQTqt6PqYZ",
    },
  },
  followup: {
    tableId: "tbl3dpgcnDBjrtMOg",
    fields: {
      submissionId: "fldKcxbWIBFBsaADS",
      participant: "fldwEyvUSqcTj9KZA",
      submittedAt: "fldcWZL9P431s021s",
      hoursPerWeek: "fldSdjTx3SCgX83LQ",
      involvement: "fldTxHzst7k1j4AAR",
      fellowshipOrJob: "fld1FfBBHwnnmslMp",
      didYouDoIt: "fldG6bVIV7O4Raqc2",
      whatGotInTheWay: "fldb3d7R1m4qPkagx",
      fieldFit: "fldB3yJ8Cari2MERt",
      careerClarity: "fldwfreehDwlkB2zA",
      hindsightFeedback: "fldlzvhpN7cP5XpmO",
      stillInTouch: "fld6Po88ym2M0mbNY",
      referrals: "fldUXwC72B1e6TzUl",
      futureHelp: "fldjFAvQMCZ3fQ591",
    },
  },
} as const;

const PAT = process.env.AIRTABLE_PAT!;

export function airtableHeaders() {
  return {
    Authorization: `Bearer ${PAT}`,
    "Content-Type": "application/json",
  };
}

export type AirtableFields = Record<string, unknown>;

export async function createAirtableRecord(
  tableId: string,
  fields: AirtableFields
) {
  const res = await fetch(
    `https://api.airtable.com/v0/${SURVEY_BASE_ID}/${tableId}`,
    {
      method: "POST",
      headers: airtableHeaders(),
      body: JSON.stringify({ records: [{ fields }] }),
    }
  );
  if (!res.ok) {
    const detail = await res.text();
    console.error("Airtable create error:", res.status, detail);
    throw new Error("Could not save your survey response. Please try again.");
  }
  return res.json();
}

export type Participant = {
  id: string;
  name: string;
  cohort?: string;
};

export async function fetchConfirmedParticipants(): Promise<Participant[]> {
  const url = new URL(
    `https://api.airtable.com/v0/${SURVEY_BASE_ID}/${APPLICATIONS_TABLE_ID}`
  );
  url.searchParams.set("pageSize", "100");
  url.searchParams.append("fields[]", "Full Name");
  url.searchParams.append("fields[]", "cohort");
  url.searchParams.append("fields[]", "Acceptance Status");
  url.searchParams.set(
    "filterByFormula",
    "{Acceptance Status} = 'Confirmed'"
  );

  const all: Participant[] = [];
  let offset: string | undefined;
  do {
    const u = new URL(url.toString());
    if (offset) u.searchParams.set("offset", offset);
    const res = await fetch(u.toString(), { headers: airtableHeaders() });
    if (!res.ok) {
      const detail = await res.text();
      console.error("Airtable participant lookup error:", res.status, detail);
      throw new Error("Could not load participant list.");
    }
    const data = (await res.json()) as {
      records: Array<{
        id: string;
        fields: { "Full Name"?: string; cohort?: string };
      }>;
      offset?: string;
    };
    for (const r of data.records) {
      const name = (r.fields["Full Name"] || "").trim();
      if (!name) continue;
      all.push({ id: r.id, name, cohort: r.fields.cohort });
    }
    offset = data.offset;
  } while (offset);

  all.sort((a, b) => a.name.localeCompare(b.name));
  return all;
}

// Fetch the most recent record from a survey table for a given participant.
// Returns the raw fields object keyed by field NAME (Airtable returns names by default).
export async function fetchLatestSurveyRecord(
  tableId: string,
  participantFieldId: string,
  participantRecordId: string
): Promise<Record<string, unknown> | null> {
  const url = new URL(
    `https://api.airtable.com/v0/${SURVEY_BASE_ID}/${tableId}`
  );
  url.searchParams.set("pageSize", "100");
  url.searchParams.set("returnFieldsByFieldId", "true");
  // Survey tables stay small; fetch + filter client-side rather than building a
  // FIND() formula against a linked-record column.
  const res = await fetch(url.toString(), { headers: airtableHeaders() });
  if (!res.ok) {
    const detail = await res.text();
    console.error("Airtable prefill lookup error:", res.status, detail);
    throw new Error("Could not load prefill data.");
  }
  const data = (await res.json()) as {
    records: Array<{ id: string; createdTime: string; fields: Record<string, unknown> }>;
  };
  const matching = data.records
    .filter((r) => {
      const v = r.fields[participantFieldId];
      return Array.isArray(v) && v.includes(participantRecordId);
    })
    .sort((a, b) => b.createdTime.localeCompare(a.createdTime));
  return matching[0]?.fields || null;
}

export function buildSubmissionId(participantName: string) {
  const date = new Date().toISOString().slice(0, 19).replace("T", " ");
  return `${participantName} - ${date}`;
}
